name: timeseriesbook
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pandas
  - matplotlib
  - scikit-learn
  - statsmodels
  - seaborn
  - openpyxl
  - jupyter
  - pip
  - pip:
    - tensorflow
    - pandas-datareader
